# Generated by Django 3.1.6 on 2021-02-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_image',
            field=models.ImageField(blank=True, null=True, upload_to='journalentryimages'),
        ),
    ]
